# Generated by Django 2.2.6 on 2020-02-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='name',
            new_name='title',
        ),
    ]
