# Generated by Django 2.2.6 on 2020-02-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200214_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(-1, 'Down'), (1, 'Up')]),
        ),
    ]
