# Generated by Django 2.2.6 on 2020-02-14 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200214_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time voted'),
        ),
    ]
